import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
import "@fontsource/instrument-serif"; 
import { Instrument_Sans, Joan } from "next/font/google";

import localFont from "next/font/local";

// // const joan = localFont({
// //   src: "./fonts/Joan-Regular.otf",
// //   variable: "--font-joan",
// // });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Include medium (500) and semi-bold (600)
  variable: "--font-instrument-sans", // Define a CSS variable name
});
export const metadata: Metadata = {
   title: "Vibeboard AI",
   description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
